services:
  postgres_test:
    image: postgres:latest
    container_name: postgres_test
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TEST_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend_test:
    build: 
      context: ./backend
      dockerfile: Dockerfile.test
    container_name: backend_test
    depends_on:
      postgres_test:
        condition: service_healthy
    mem_limit: 2g 
    environment:
      DATABASE_URL: ${TEST_DB_URL}
