services:
  postgres:
    image: postgres:14
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    logging:
      driver: loki
      options:
        loki-url: "http://83.222.17.10:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"
        loki-batch-wait: "1s"
        loki-external-labels: "job=postgres,service=db"

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
    environment:
      - WAIT_HOSTS=postgres:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - FORWARDED_ALLOW_IPS=*
    expose:
      - "8000"
    logging:
      driver: loki
      options:
        loki-url: "http://83.222.17.10:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"
        loki-batch-wait: "1s"
        loki-external-labels: "job=backend,service=api"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      NODE_OPTIONS: "--openssl-legacy-provider"
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  prometheus: 
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml
    command:
      - '--config.file=/etc/prometheus.yml'
    ports:
      - "9090:9090"
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=https://libnet.site/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  grafana-storage: