services:
  postgres_test:
    image: postgres:latest
    container_name: postgres_test
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

  backend_test:
    build: 
      context: ./backend
      dockerfile: Dockerfile.test
    depends_on:
      - postgres_test
    environment:
      DATABASE_URL: ${TEST_DB_URL}
