FROM python:3.12

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && RUN pip install sqlmodel alembic psycopg2-binary

COPY . .

CMD ["sh", "-c", "alembic upgrade head && pytest"]