FROM python:3.12-alpine

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt sqlmodel alembic psycopg2-binary

COPY . .

CMD ["sh", "-c", "alembic upgrade head && pytest"]