name: CI/CD Pipeline  

on:
  push:
    branches: 
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      TEST_DB_USER: ${{ secrets.TEST_DB_USER }}
      TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
      TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
      TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Start test containers
        run: docker compose -f docker-compose.test.yml up --build -d

      - name: Check container status
        run: docker compose -f docker-compose.test.yml ps

      - name: Show postgres logs
        run: docker compose -f docker-compose.test.yml logs postgres_test
          
      - name: Run migrations
        run: |
          docker compose -f docker-compose.test.yml exec backend_test alembic upgrade head --verbose
  
      - name: Run tests
        run: |
          docker compose -f docker-compose.test.yml exec backend_test pytest -v --cov=app

      - name: Stop test containers
        if: always()
        run: docker compose -f docker-compose.test.yml down

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy over SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<EOF
            cd ${{ secrets.PROJECT_DIR }}
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
